# -*- coding: utf-8 -*-
"""Entrada_Saida_POO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-Am-C2EwUWMYwzwQ0zD5_M4sFmGbSas
"""

class Triangulo:
  def __init__(self):
    self.base = int(input("Digite o valor da base: "))
    self.l2 = int(input("Digite o valor do segundo lado: "))
    self.l3 = int(input("Digite o valor do terceiro lado: "))

    self.perimetro = self.base + self.l2 + self.l3

    if self.l2 == self.l3 and self.l2 != self.base:
      self.area = (self.l2*self.base)/2
      print("É um triangulo Isóceles, de área: ", self.area)
      print("E perímetro: ", self.perimetro)
      print("\n")
    
    elif self.l2 == self.l3 and self.l2 == self.base:
      self.area = (self.base*self.l2)/2
      print("É um triângulo equilátero, de área: ", self.area)
      print("E perímetro: ", self.perimetro)
      print("\n")

    elif self.l2 != self.l3 and self.l2 != self.base and self.l3 != self.base: 
      self.area = (self.base*self.l2)/2
      print("Tomando o lado de um lado, como altura, temos: ")
      print("É um triangulo Escaleno, de área: ", self.area)
      print("E perímetro: ", self.perimetro)
      print("\n")

class Quadrado: 
  def __init__(self):
    self.lado = int(input("Digite o valor do lado: "))

    self.area = self.lado**2
    self.perimetro = self.lado * 4

    print("A area do quadrado é: ", self.area)
    print("O perímetro do quadrado é: ", self.perimetro)
    print("\n")

def main():
  a = 5
  while a != 0:
    print("Para calcular um quadrado, digite 1;")
    print("Para calcular um triângulo, digite 2.")
    print("Digite 0 para sair: ")
    a = int(input("Escolha uma opção: "))

    if a == 1:
      Quadrado()

    elif a == 2: 
      Triangulo()
    
    elif a == 0:
      print("Saindo")

    else:
      print("Entrada inválida.")

main()

